export const Country = [
  { country: 'Afghanistan', code: '+93', countryCode: 'af' },
  { country: 'Albania', code: '+355', countryCode: 'al' },
  { country: 'Algeria', code: '+213', countryCode: 'dz' },
  { country: 'Andorra', code: '+376', countryCode: 'ad' },
  { country: 'Angola', code: '+244', countryCode: 'ao' },
  { country: 'Antigua and Barbuda', code: '+1-268', countryCode: 'ag' },
  { country: 'Argentina', code: '+54', countryCode: 'ar' },
  { country: 'Armenia', code: '+374', countryCode: 'am' },
  { country: 'Australia', code: '+61', countryCode: 'au' },
  { country: 'Austria', code: '+43', countryCode: 'at' },
  { country: 'Azerbaijan', code: '+994', countryCode: 'az' },
  { country: 'Bahamas', code: '+1-242', countryCode: 'bs' },
  { country: 'Bahrain', code: '+973', countryCode: 'bh' },
  { country: 'Bangladesh', code: '+880', countryCode: 'bd' },
  { country: 'Barbados', code: '+1-246', countryCode: 'bb' },
  { country: 'Belarus', code: '+375', countryCode: 'by' },
  { country: 'Belgium', code: '+32', countryCode: 'be' },
  { country: 'Belize', code: '+501', countryCode: 'bz' },
  { country: 'Benin', code: '+229', countryCode: 'bj' },
  { country: 'Bhutan', code: '+975', countryCode: 'bt' },
  { country: 'Bolivia', code: '+591', countryCode: 'bo' },
  { country: 'Bosnia and Herzegovina', code: '+387', countryCode: 'ba' },
  { country: 'Botswana', code: '+267', countryCode: 'bw' },
  { country: 'Brazil', code: '+55', countryCode: 'br' },
  { country: 'Brunei', code: '+673', countryCode: 'bn' },
  { country: 'Bulgaria', code: '+359', countryCode: 'bg' },
  { country: 'Burkina Faso', code: '+226', countryCode: 'bf' },
  { country: 'Burundi', code: '+257', countryCode: 'bi' },
  { country: 'Cambodia', code: '+855', countryCode: 'kh' },
  { country: 'Cameroon', code: '+237', countryCode: 'cm' },
  { country: 'Canada', code: '+1', countryCode: 'ca' },
  { country: 'Cape Verde', code: '+238', countryCode: 'cv' },
  { country: 'Central African Republic', code: '+236', countryCode: 'cf' },
  { country: 'Chad', code: '+235', countryCode: 'td' },
  { country: 'Chile', code: '+56', countryCode: 'cl' },
  { country: 'China', code: '+86', countryCode: 'cn' },
  { country: 'Colombia', code: '+57', countryCode: 'co' },
  { country: 'Comoros', code: '+269', countryCode: 'km' },
  { country: 'Congo', code: '+242', countryCode: 'cg' },
  { country: 'Costa Rica', code: '+506', countryCode: 'cr' },
  { country: 'Croatia', code: '+385', countryCode: 'hr' },
  { country: 'Cuba', code: '+53', countryCode: 'cu' },
  { country: 'Cyprus', code: '+357', countryCode: 'cy' },
  { country: 'Czech Republic', code: '+420', countryCode: 'cz' },
  { country: 'Denmark', code: '+45', countryCode: 'dk' },
  { country: 'Djibouti', code: '+253', countryCode: 'dj' },
  { country: 'Dominica', code: '+1-767', countryCode: 'dm' },
  { country: 'Dominican Republic', code: '+1-809, +1-829, +1-849', countryCode: 'do' },
  { country: 'East Timor', code: '+670', countryCode: 'tl' },
  { country: 'Ecuador', code: '+593', countryCode: 'ec' },
  { country: 'Egypt', code: '+20', countryCode: 'eg' },
  { country: 'El Salvador', code: '+503', countryCode: 'sv' },
  { country: 'Equatorial Guinea', code: '+240', countryCode: 'gq' },
  { country: 'Eritrea', code: '+291', countryCode: 'er' },
  { country: 'Estonia', code: '+372', countryCode: 'ee' },
  { country: 'Ethiopia', code: '+251', countryCode: 'et' },
  { country: 'Fiji', code: '+679', countryCode: 'fj' },
  { country: 'Finland', code: '+358', countryCode: 'fi' },
  { country: 'France', code: '+33', countryCode: 'fr' },
  { country: 'Gabon', code: '+241', countryCode: 'ga' },
  { country: 'Gambia', code: '+220', countryCode: 'gm' },
  { country: 'Georgia', code: '+995', countryCode: 'ge' },
  { country: 'Germany', code: '+49', countryCode: 'de' },
  { country: 'Ghana', code: '+233', countryCode: 'gh' },
  { country: 'Greece', code: '+30', countryCode: 'gr' },
  { country: 'Grenada', code: '+1-473', countryCode: 'gd' },
  { country: 'Guatemala', code: '+502', countryCode: 'gt' },
  { country: 'Guinea', code: '+224', countryCode: 'gn' },
  { country: 'Guinea-Bissau', code: '+245', countryCode: 'gw' },
  { country: 'Guyana', code: '+592', countryCode: 'gy' },
  { country: 'Haiti', code: '+509', countryCode: 'ht' },
  { country: 'Honduras', code: '+504', countryCode: 'hn' },
  { country: 'Hungary', code: '+36', countryCode: 'hu' },
  { country: 'Iceland', code: '+354', countryCode: 'is' },
  { country: 'India', code: '+91', countryCode: 'in' },
  { country: 'Indonesia', code: '+62', countryCode: 'id' },
  { country: 'Iran', code: '+98', countryCode: 'ir' },
  { country: 'Iraq', code: '+964', countryCode: 'iq' },
  { country: 'Ireland', code: '+353', countryCode: 'ie' },
  { country: 'Israel', code: '+972', countryCode: 'il' },
  { country: 'Italy', code: '+39', countryCode: 'it' },
  { country: 'Jamaica', code: '+1-876', countryCode: 'jm' },
  { country: 'Japan', code: '+81', countryCode: 'jp' },
  { country: 'Jordan', code: '+962', countryCode: 'jo' },
  { country: 'Kazakhstan', code: '+7', countryCode: 'kz' },
  { country: 'Kenya', code: '+254', countryCode: 'ke' },
  { country: 'Kiribati', code: '+686', countryCode: 'ki' },
  { country: 'Korea, North', code: '+850', countryCode: 'kp' },
  { country: 'Korea, South', code: '+82', countryCode: 'kr' },
  { country: 'Kuwait', code: '+965', countryCode: 'kw' },
  { country: 'Kyrgyzstan', code: '+996', countryCode: 'kg' },
  { country: 'Laos', code: '+856', countryCode: 'la' },
  { country: 'Latvia', code: '+371', countryCode: 'lv' },
  { country: 'Lebanon', code: '+961', countryCode: 'lb' },
  { country: 'Lesotho', code: '+266', countryCode: 'ls' },
  { country: 'Liberia', code: '+231', countryCode: 'lr' },
  { country: 'Libya', code: '+218', countryCode: 'ly' },
  { country: 'Liechtenstein', code: '+423', countryCode: 'li' },
  { country: 'Lithuania', code: '+370', countryCode: 'lt' },
  { country: 'Luxembourg', code: '+352', countryCode: 'lu' },
  { country: 'Macedonia', code: '+389', countryCode: 'mk' },
  { country: 'Madagascar', code: '+261', countryCode: 'mg' },
  { country: 'Malawi', code: '+265', countryCode: 'mw' },
  { country: 'Malaysia', code: '+60', countryCode: 'my' },
  { country: 'Maldives', code: '+960', countryCode: 'mv' },
  { country: 'Mali', code: '+223', countryCode: 'ml' },
  { country: 'Malta', code: '+356', countryCode: 'mt' },
  { country: 'Marshall Islands', code: '+692', countryCode: 'mh' },
  { country: 'Mauritania', code: '+222', countryCode: 'mr' },
  { country: 'Mauritius', code: '+230', countryCode: 'mu' },
  { country: 'Mexico', code: '+52', countryCode: 'mx' },
  { country: 'Micronesia', code: '+691', countryCode: 'fm' },
  { country: 'Moldova', code: '+373', countryCode: 'md' },
  { country: 'Monaco', code: '+377', countryCode: 'mc' },
  { country: 'Mongolia', code: '+976', countryCode: 'mn' },
  { country: 'Montenegro', code: '+382', countryCode: 'me' },
  { country: 'Morocco', code: '+212', countryCode: 'ma' },
  { country: 'Mozambique', code: '+258', countryCode: 'mz' },
  { country: 'Myanmar', code: '+95', countryCode: 'mm' },
  { country: 'Namibia', code: '+264', countryCode: 'na' },
  { country: 'Nauru', code: '+674', countryCode: 'nr' },
  { country: 'Nepal', code: '+977', countryCode: 'np' },
  { country: 'Netherlands', code: '+31', countryCode: 'nl' },
  { country: 'New Zealand', code: '+64', countryCode: 'nz' },
  { country: 'Nicaragua', code: '+505', countryCode: 'ni' },
  { country: 'Niger', code: '+227', countryCode: 'ne' },
  { country: 'Nigeria', code: '+234', countryCode: 'ng' },
  { country: 'Norway', code: '+47', countryCode: 'no' },
  { country: 'Oman', code: '+968', countryCode: 'om' },
  { country: 'Pakistan', code: '+92', countryCode: 'pk' },
  { country: 'Palau', code: '+680', countryCode: 'pw' },
  { country: 'Palestine', code: '+970', countryCode: 'ps' },
  { country: 'Panama', code: '+507', countryCode: 'pa' },
  { country: 'Papua New Guinea', code: '+675', countryCode: 'pg' },
  { country: 'Paraguay', code: '+595', countryCode: 'py' },
  { country: 'Peru', code: '+51', countryCode: 'pe' },
  { country: 'Philippines', code: '+63', countryCode: 'ph' },
  { country: 'Poland', code: '+48', countryCode: 'pl' },
  { country: 'Portugal', code: '+351', countryCode: 'pt' },
  { country: 'Qatar', code: '+974', countryCode: 'qa' },
  { country: 'Romania', code: '+40', countryCode: 'ro' },
  { country: 'Russia', code: '+7', countryCode: 'ru' },
  { country: 'Rwanda', code: '+250', countryCode: 'rw' },
  { country: 'Saint Kitts and Nevis', code: '+1-869', countryCode: 'kn' },
  { country: 'Saint Lucia', code: '+1-758', countryCode: 'lc' },
  { country: 'Saint Vincent and the Grenadines', code: '+1-784', countryCode: 'vc' },
  { country: 'Samoa', code: '+685', countryCode: 'ws' },
  { country: 'San Marino', code: '+378', countryCode: 'sm' },
  { country: 'Sao Tome and Principe', code: '+239', countryCode: 'st' },
  { country: 'Saudi Arabia', code: '+966', countryCode: 'sa' },
  { country: 'Senegal', code: '+221', countryCode: 'sn' },
  { country: 'Serbia', code: '+381', countryCode: 'rs' },
  { country: 'Seychelles', code: '+248', countryCode: 'sc' },
  { country: 'Sierra Leone', code: '+232', countryCode: 'sl' },
  { country: 'Singapore', code: '+65', countryCode: 'sg' },
  { country: 'Slovakia', code: '+421', countryCode: 'sk' },
  { country: 'Slovenia', code: '+386', countryCode: 'si' },
  { country: 'Solomon Islands', code: '+677', countryCode: 'sb' },
  { country: 'Somalia', code: '+252', countryCode: 'so' },
  { country: 'South Africa', code: '+27', countryCode: 'za' },
  { country: 'South Sudan', code: '+211', countryCode: 'ss' },
  { country: 'Spain', code: '+34', countryCode: 'es' },
  { country: 'Sri Lanka', code: '+94', countryCode: 'lk' },
  { country: 'Sudan', code: '+249', countryCode: 'sd' },
  { country: 'Suriname', code: '+597', countryCode: 'sr' },
  { country: 'Sweden', code: '+46', countryCode: 'se' },
  { country: 'Switzerland', code: '+41', countryCode: 'ch' },
  { country: 'Syria', code: '+963', countryCode: 'sy' },
  { country: 'Taiwan', code: '+886', countryCode: 'tw' },
  { country: 'Tajikistan', code: '+992', countryCode: 'tj' },
  { country: 'Tanzania', code: '+255', countryCode: 'tz' },
  { country: 'Thailand', code: '+66', countryCode: 'th' },
  { country: 'Togo', code: '+228', countryCode: 'tg' },
  { country: 'Tonga', code: '+676', countryCode: 'to' },
  { country: 'Trinidad and Tobago', code: '+1-868', countryCode: 'tt' },
  { country: 'Tunisia', code: '+216', countryCode: 'tn' },
  { country: 'Turkey', code: '+90', countryCode: 'tr' },
  { country: 'Turkmenistan', code: '+993', countryCode: 'tm' },
  { country: 'Tuvalu', code: '+688', countryCode: 'tv' },
  { country: 'Uganda', code: '+256', countryCode: 'ug' },
  { country: 'Ukraine', code: '+380', countryCode: 'ua' },
  { country: 'United Arab Emirates', code: '+971', countryCode: 'ae' },
  { country: 'United Kingdom', code: '+44', countryCode: 'gb' },
  { country: 'United States', code: '+1', countryCode: 'us' },
  { country: 'Uruguay', code: '+598', countryCode: 'uy' },
  { country: 'Uzbekistan', code: '+998', countryCode: 'uz' },
  { country: 'Vanuatu', code: '+678', countryCode: 'vu' },
  { country: 'Vatican City', code: '+379', countryCode: 'va' },
  { country: 'Venezuela', code: '+58', countryCode: 've' },
  { country: 'Vietnam', code: '+84', countryCode: 'vn' },
  { country: 'Yemen', code: '+967', countryCode: 'ye' },
  { country: 'Zambia', code: '+260', countryCode: 'zm' },
  { country: 'Zimbabwe', code: '+263', countryCode: 'zw' },
];


